name: Build github pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2.21.0
        with:
          channel: stable
        name: Set up Flutter

      - run: echo $FLUTTER_SECRETS | base64 -d > .env
        env:
          FLUTTER_SECRETS: ${{ secrets.FLUTTER_SECRETS }}

      - name: Get dependencies
        run: flutter pub get && flutter pub upgrade

      - name: Build
        run: flutter build web --release --dart-define-from-file .env

      - name: Inject CNAME
        run: echo "tavolara.dvdbnc.dev" > build/web/CNAME

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: build/web # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message